/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.docl.impl;

import fr.inria.diverse.docl.docl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DoclFactoryImpl extends EFactoryImpl implements DoclFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DoclFactory init()
  {
    try
    {
      DoclFactory theDoclFactory = (DoclFactory)EPackage.Registry.INSTANCE.getEFactory(DoclPackage.eNS_URI);
      if (theDoclFactory != null)
      {
        return theDoclFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DoclFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DoclFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DoclPackage.MODULE: return createModule();
      case DoclPackage.OCL_MODEL: return createOclModel();
      case DoclPackage.URI_: return createURI_();
      case DoclPackage.IMPORT: return createImport();
      case DoclPackage.MODULE_ELEMENT: return createModuleElement();
      case DoclPackage.QUERY: return createQuery();
      case DoclPackage.OCL_EXPRESSION: return createOclExpression();
      case DoclPackage.ITERATOR: return createIterator();
      case DoclPackage.LOCAL_VARIABLE: return createLocalVariable();
      case DoclPackage.TUPLE_PART: return createTuplePart();
      case DoclPackage.PRIMITIVE_EXP: return createPrimitiveExp();
      case DoclPackage.NUMBER_LITERAL_EXP: return createNumberLiteralExp();
      case DoclPackage.STRING_LITERAL_EXP: return createStringLiteralExp();
      case DoclPackage.BOOLEAN_LITERAL_EXP: return createBooleanLiteralExp();
      case DoclPackage.UNLIMITED_NATURAL_LITERAL_EXP: return createUnlimitedNaturalLiteralExp();
      case DoclPackage.INVALID_LITERAL_EXP: return createInvalidLiteralExp();
      case DoclPackage.NULL_LITERAL_EXP: return createNullLiteralExp();
      case DoclPackage.IF_EXP: return createIfExp();
      case DoclPackage.OCL_TYPE: return createOclType();
      case DoclPackage.OCL_MODEL_ELEMENT_EXP: return createOclModelElementExp();
      case DoclPackage.ENV_TYPE: return createEnvType();
      case DoclPackage.LAMBDA_TYPE: return createLambdaType();
      case DoclPackage.MAP_TYPE: return createMapType();
      case DoclPackage.TUPLE_TYPE: return createTupleType();
      case DoclPackage.OCL_ANY_TYPE: return createOclAnyType();
      case DoclPackage.SET_TYPE: return createSetType();
      case DoclPackage.SEQUENCE_TYPE: return createSequenceType();
      case DoclPackage.ORDERED_SET_TYPE: return createOrderedSetType();
      case DoclPackage.BAG_TYPE: return createBagType();
      case DoclPackage.REAL_TYPE: return createRealType();
      case DoclPackage.INTEGER_TYPE: return createIntegerType();
      case DoclPackage.BOOLEAN_TYPE: return createBooleanType();
      case DoclPackage.STRING_TYPE: return createStringType();
      case DoclPackage.BOOL_OP_CALL_EXP: return createBoolOpCallExp();
      case DoclPackage.EQ_OP_CALL_EXP: return createEqOpCallExp();
      case DoclPackage.COM_OP_CALL_EXP: return createComOpCallExp();
      case DoclPackage.ADD_OP_CALL_EXP: return createAddOpCallExp();
      case DoclPackage.MUL_OP_CALL_EXP: return createMulOpCallExp();
      case DoclPackage.NAVIGATION_EXP: return createNavigationExp();
      case DoclPackage.COLLECTION_OP_CALL_EXP: return createCollectionOpCallExp();
      case DoclPackage.ITERATE_EXP: return createIterateExp();
      case DoclPackage.ITERATOR_EXP: return createIteratorExp();
      case DoclPackage.NAVIGATION_OR_ATTRIBUTE_CALL: return createNavigationOrAttributeCall();
      case DoclPackage.OPERATION_CALL: return createOperationCall();
      case DoclPackage.LAMBDA_EXP: return createLambdaExp();
      case DoclPackage.TUPLE_EXP: return createTupleExp();
      case DoclPackage.ELSE_IF_THEN_EXP: return createElseIfThenExp();
      case DoclPackage.SELF_EXP: return createSelfExp();
      case DoclPackage.NESTED_EXP: return createNestedExp();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Module createModule()
  {
    ModuleImpl module = new ModuleImpl();
    return module;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OclModel createOclModel()
  {
    OclModelImpl oclModel = new OclModelImpl();
    return oclModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public URI_ createURI_()
  {
    URI_Impl urI_ = new URI_Impl();
    return urI_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModuleElement createModuleElement()
  {
    ModuleElementImpl moduleElement = new ModuleElementImpl();
    return moduleElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Query createQuery()
  {
    QueryImpl query = new QueryImpl();
    return query;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OclExpression createOclExpression()
  {
    OclExpressionImpl oclExpression = new OclExpressionImpl();
    return oclExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Iterator createIterator()
  {
    IteratorImpl iterator = new IteratorImpl();
    return iterator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LocalVariable createLocalVariable()
  {
    LocalVariableImpl localVariable = new LocalVariableImpl();
    return localVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TuplePart createTuplePart()
  {
    TuplePartImpl tuplePart = new TuplePartImpl();
    return tuplePart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PrimitiveExp createPrimitiveExp()
  {
    PrimitiveExpImpl primitiveExp = new PrimitiveExpImpl();
    return primitiveExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NumberLiteralExp createNumberLiteralExp()
  {
    NumberLiteralExpImpl numberLiteralExp = new NumberLiteralExpImpl();
    return numberLiteralExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StringLiteralExp createStringLiteralExp()
  {
    StringLiteralExpImpl stringLiteralExp = new StringLiteralExpImpl();
    return stringLiteralExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BooleanLiteralExp createBooleanLiteralExp()
  {
    BooleanLiteralExpImpl booleanLiteralExp = new BooleanLiteralExpImpl();
    return booleanLiteralExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UnlimitedNaturalLiteralExp createUnlimitedNaturalLiteralExp()
  {
    UnlimitedNaturalLiteralExpImpl unlimitedNaturalLiteralExp = new UnlimitedNaturalLiteralExpImpl();
    return unlimitedNaturalLiteralExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InvalidLiteralExp createInvalidLiteralExp()
  {
    InvalidLiteralExpImpl invalidLiteralExp = new InvalidLiteralExpImpl();
    return invalidLiteralExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NullLiteralExp createNullLiteralExp()
  {
    NullLiteralExpImpl nullLiteralExp = new NullLiteralExpImpl();
    return nullLiteralExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IfExp createIfExp()
  {
    IfExpImpl ifExp = new IfExpImpl();
    return ifExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OclType createOclType()
  {
    OclTypeImpl oclType = new OclTypeImpl();
    return oclType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OclModelElementExp createOclModelElementExp()
  {
    OclModelElementExpImpl oclModelElementExp = new OclModelElementExpImpl();
    return oclModelElementExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnvType createEnvType()
  {
    EnvTypeImpl envType = new EnvTypeImpl();
    return envType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LambdaType createLambdaType()
  {
    LambdaTypeImpl lambdaType = new LambdaTypeImpl();
    return lambdaType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MapType createMapType()
  {
    MapTypeImpl mapType = new MapTypeImpl();
    return mapType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TupleType createTupleType()
  {
    TupleTypeImpl tupleType = new TupleTypeImpl();
    return tupleType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OclAnyType createOclAnyType()
  {
    OclAnyTypeImpl oclAnyType = new OclAnyTypeImpl();
    return oclAnyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SetType createSetType()
  {
    SetTypeImpl setType = new SetTypeImpl();
    return setType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SequenceType createSequenceType()
  {
    SequenceTypeImpl sequenceType = new SequenceTypeImpl();
    return sequenceType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OrderedSetType createOrderedSetType()
  {
    OrderedSetTypeImpl orderedSetType = new OrderedSetTypeImpl();
    return orderedSetType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BagType createBagType()
  {
    BagTypeImpl bagType = new BagTypeImpl();
    return bagType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RealType createRealType()
  {
    RealTypeImpl realType = new RealTypeImpl();
    return realType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IntegerType createIntegerType()
  {
    IntegerTypeImpl integerType = new IntegerTypeImpl();
    return integerType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BooleanType createBooleanType()
  {
    BooleanTypeImpl booleanType = new BooleanTypeImpl();
    return booleanType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StringType createStringType()
  {
    StringTypeImpl stringType = new StringTypeImpl();
    return stringType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BoolOpCallExp createBoolOpCallExp()
  {
    BoolOpCallExpImpl boolOpCallExp = new BoolOpCallExpImpl();
    return boolOpCallExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EqOpCallExp createEqOpCallExp()
  {
    EqOpCallExpImpl eqOpCallExp = new EqOpCallExpImpl();
    return eqOpCallExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComOpCallExp createComOpCallExp()
  {
    ComOpCallExpImpl comOpCallExp = new ComOpCallExpImpl();
    return comOpCallExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AddOpCallExp createAddOpCallExp()
  {
    AddOpCallExpImpl addOpCallExp = new AddOpCallExpImpl();
    return addOpCallExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MulOpCallExp createMulOpCallExp()
  {
    MulOpCallExpImpl mulOpCallExp = new MulOpCallExpImpl();
    return mulOpCallExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NavigationExp createNavigationExp()
  {
    NavigationExpImpl navigationExp = new NavigationExpImpl();
    return navigationExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CollectionOpCallExp createCollectionOpCallExp()
  {
    CollectionOpCallExpImpl collectionOpCallExp = new CollectionOpCallExpImpl();
    return collectionOpCallExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IterateExp createIterateExp()
  {
    IterateExpImpl iterateExp = new IterateExpImpl();
    return iterateExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IteratorExp createIteratorExp()
  {
    IteratorExpImpl iteratorExp = new IteratorExpImpl();
    return iteratorExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NavigationOrAttributeCall createNavigationOrAttributeCall()
  {
    NavigationOrAttributeCallImpl navigationOrAttributeCall = new NavigationOrAttributeCallImpl();
    return navigationOrAttributeCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OperationCall createOperationCall()
  {
    OperationCallImpl operationCall = new OperationCallImpl();
    return operationCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LambdaExp createLambdaExp()
  {
    LambdaExpImpl lambdaExp = new LambdaExpImpl();
    return lambdaExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TupleExp createTupleExp()
  {
    TupleExpImpl tupleExp = new TupleExpImpl();
    return tupleExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ElseIfThenExp createElseIfThenExp()
  {
    ElseIfThenExpImpl elseIfThenExp = new ElseIfThenExpImpl();
    return elseIfThenExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SelfExp createSelfExp()
  {
    SelfExpImpl selfExp = new SelfExpImpl();
    return selfExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NestedExp createNestedExp()
  {
    NestedExpImpl nestedExp = new NestedExpImpl();
    return nestedExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DoclPackage getDoclPackage()
  {
    return (DoclPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DoclPackage getPackage()
  {
    return DoclPackage.eINSTANCE;
  }

} //DoclFactoryImpl
