/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl;

import fr.inria.diverse.docl.AbstractDOclRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DOclRuntimeModule extends AbstractDOclRuntimeModule {
}
