/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl;

import fr.inria.diverse.docl.DOclStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DOclStandaloneSetup extends DOclStandaloneSetupGenerated {
  public static void doSetup() {
    DOclStandaloneSetup _dOclStandaloneSetup = new DOclStandaloneSetup();
    _dOclStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
