/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import fr.inria.diverse.docl.docl.Module

@RunWith(XtextRunner)
@InjectWith(DOclInjectorProvider)
class DOclParsingTest{

	@Inject
	ParseHelper<Module> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			module test 
			
			@@source classMeta 
			@@input classInstance
		''')
		Assert.assertNotNull(result)
	}

}
