/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DOclStandaloneSetup extends DOclStandaloneSetupGenerated {

	def static void doSetup() {
		new DOclStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
