/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.ui.tests;

import com.google.inject.Injector;
import fr.inria.diverse.docl.ui.internal.DoclActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DOclUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DoclActivator.getInstance().getInjector("fr.inria.diverse.docl.DOcl");
	}

}
