/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.ui;

import com.google.inject.Injector;
import fr.inria.diverse.docl.ui.internal.DoclActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DOclExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DoclActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DoclActivator.getInstance().getInjector(DoclActivator.FR_INRIA_DIVERSE_DOCL_DOCL);
	}
	
}
