/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.tests;

import com.google.inject.Inject;
import fr.inria.diverse.docl.docl.Module;
import fr.inria.diverse.docl.tests.DOclInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(DOclInjectorProvider.class)
@SuppressWarnings("all")
public class DOclParsingTest {
  @Inject
  private ParseHelper<Module> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("module test ");
      _builder.newLine();
      _builder.newLine();
      _builder.append("@@source classMeta ");
      _builder.newLine();
      _builder.append("@@input classInstance");
      _builder.newLine();
      final Module result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
