/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDOclScopeProvider extends DelegatingScopeProvider {
}
