/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.validation;

import fr.inria.diverse.docl.validation.AbstractDOclValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DOclValidator extends AbstractDOclValidator {
}
