/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.parser.antlr;

import com.google.inject.Inject;
import fr.inria.diverse.docl.parser.antlr.internal.InternalDOclParser;
import fr.inria.diverse.docl.services.DOclGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DOclParser extends AbstractAntlrParser {

	@Inject
	private DOclGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDOclParser createParser(XtextTokenStream stream) {
		return new InternalDOclParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}

	public DOclGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DOclGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
