/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.ui.contentassist;

import fr.inria.diverse.docl.ui.contentassist.AbstractDOclProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DOclProposalProvider extends AbstractDOclProposalProvider {
}
