/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.docl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Else If Then Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.docl.docl.ElseIfThenExp#getCondition <em>Condition</em>}</li>
 *   <li>{@link fr.inria.diverse.docl.docl.ElseIfThenExp#getThen <em>Then</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.docl.docl.DoclPackage#getElseIfThenExp()
 * @model
 * @generated
 */
public interface ElseIfThenExp extends OclExpression
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(OclExpression)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getElseIfThenExp_Condition()
   * @model containment="true"
   * @generated
   */
  OclExpression getCondition();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.ElseIfThenExp#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(OclExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(OclExpression)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getElseIfThenExp_Then()
   * @model containment="true"
   * @generated
   */
  OclExpression getThen();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.ElseIfThenExp#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(OclExpression value);

} // ElseIfThenExp
