/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.docl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invalid Literal Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.docl.docl.DoclPackage#getInvalidLiteralExp()
 * @model
 * @generated
 */
public interface InvalidLiteralExp extends PrimitiveExp
{
} // InvalidLiteralExp
