/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.docl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Iterator Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.docl.docl.IteratorExp#getIterators <em>Iterators</em>}</li>
 *   <li>{@link fr.inria.diverse.docl.docl.IteratorExp#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.docl.docl.DoclPackage#getIteratorExp()
 * @model
 * @generated
 */
public interface IteratorExp extends OclExpression
{
  /**
   * Returns the value of the '<em><b>Iterators</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.docl.docl.Iterator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iterators</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterators</em>' containment reference list.
   * @see fr.inria.diverse.docl.docl.DoclPackage#getIteratorExp_Iterators()
   * @model containment="true"
   * @generated
   */
  EList<Iterator> getIterators();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(OclExpression)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getIteratorExp_Body()
   * @model containment="true"
   * @generated
   */
  OclExpression getBody();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.IteratorExp#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(OclExpression value);

} // IteratorExp
