/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.docl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.docl.docl.DoclPackage#getModuleElement()
 * @model
 * @generated
 */
public interface ModuleElement extends EObject
{
} // ModuleElement
