/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.docl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ocl Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.docl.docl.OclExpression#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.docl.docl.OclExpression#getVariable <em>Variable</em>}</li>
 *   <li>{@link fr.inria.diverse.docl.docl.OclExpression#getIn <em>In</em>}</li>
 *   <li>{@link fr.inria.diverse.docl.docl.OclExpression#getTarget <em>Target</em>}</li>
 *   <li>{@link fr.inria.diverse.docl.docl.OclExpression#getModel <em>Model</em>}</li>
 *   <li>{@link fr.inria.diverse.docl.docl.OclExpression#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.docl.docl.DoclPackage#getOclExpression()
 * @model
 * @generated
 */
public interface OclExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getOclExpression_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.OclExpression#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(LocalVariable)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getOclExpression_Variable()
   * @model containment="true"
   * @generated
   */
  LocalVariable getVariable();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.OclExpression#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(LocalVariable value);

  /**
   * Returns the value of the '<em><b>In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' containment reference.
   * @see #setIn(OclExpression)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getOclExpression_In()
   * @model containment="true"
   * @generated
   */
  OclExpression getIn();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.OclExpression#getIn <em>In</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In</em>' containment reference.
   * @see #getIn()
   * @generated
   */
  void setIn(OclExpression value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(OclExpression)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getOclExpression_Target()
   * @model containment="true"
   * @generated
   */
  OclExpression getTarget();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.OclExpression#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(OclExpression value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference.
   * @see #setModel(OclModel)
   * @see fr.inria.diverse.docl.docl.DoclPackage#getOclExpression_Model()
   * @model containment="true"
   * @generated
   */
  OclModel getModel();

  /**
   * Sets the value of the '{@link fr.inria.diverse.docl.docl.OclExpression#getModel <em>Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' containment reference.
   * @see #getModel()
   * @generated
   */
  void setModel(OclModel value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' attribute list.
   * @see fr.inria.diverse.docl.docl.DoclPackage#getOclExpression_Elements()
   * @model unique="false"
   * @generated
   */
  EList<String> getElements();

} // OclExpression
