/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.docl.docl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tuple Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.docl.docl.DoclPackage#getTupleType()
 * @model
 * @generated
 */
public interface TupleType extends OclType
{
} // TupleType
